-- =============================================================================
-- 04 · Establishment — posts, hierarchy, sanctioned strength, mappings
-- =============================================================================

SET search_path TO um, public;

-- POSTS_MASTER
CREATE TABLE IF NOT EXISTS um.posts_master (
  post_code      varchar(40)  PRIMARY KEY,
  post_name      varchar(160) NOT NULL,
  division_code  varchar(40)  NOT NULL
                 REFERENCES um.division_master (division_code),
  is_active      boolean      NOT NULL DEFAULT true,
  created_at     timestamptz  NOT NULL DEFAULT now(),
  updated_at     timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT uk_post_name UNIQUE (post_name)
);

COMMENT ON TABLE um.posts_master IS
  'DSR establishment posts — distinct from Role Master (FR-UM-046, FR-UM-049)';

-- OFFICER_HIERARCHY_NODE (FR-UM-043 / FR-UM-044)
CREATE TABLE IF NOT EXISTS um.officer_hierarchy_node (
  node_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_code       varchar(40) NOT NULL
                  REFERENCES um.posts_master (post_code),
  parent_node_id  bigint
                  REFERENCES um.officer_hierarchy_node (node_id),
  division_code   varchar(40)
                  REFERENCES um.division_master (division_code),
  display_order   integer     NOT NULL DEFAULT 0,
  effective_from  date,
  effective_to    date,
  is_active       boolean     NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uk_officer_hierarchy_post UNIQUE (post_code),
  CONSTRAINT ck_officer_hierarchy_dates CHECK (
    effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from
  )
);

CREATE INDEX IF NOT EXISTS ix_officer_hierarchy_parent
  ON um.officer_hierarchy_node (parent_node_id);

COMMENT ON TABLE um.officer_hierarchy_node IS
  'Reporting tree of Posts (not people) — FR-UM-043';

COMMENT ON COLUMN um.officer_hierarchy_node.division_code IS
  'Division / Branch attribute of the hierarchy node (FR-UM-043, Section 6.5.7 attributes table)';
COMMENT ON COLUMN um.officer_hierarchy_node.effective_from IS
  'Optional validity window start of the hierarchy link (Section 6.5.7 attributes table)';
COMMENT ON COLUMN um.officer_hierarchy_node.effective_to IS
  'Optional validity window end of the hierarchy link (Section 6.5.7 attributes table)';

-- POST_OFFICE_TYPE_ALLOWED (FR-UM-078)
CREATE TABLE IF NOT EXISTS um.post_office_type_allowed (
  post_code         varchar(40) NOT NULL
                    REFERENCES um.posts_master (post_code),
  office_type_code  varchar(40) NOT NULL
                    REFERENCES um.office_type (office_type_code),
  PRIMARY KEY (post_code, office_type_code)
);

COMMENT ON TABLE um.post_office_type_allowed IS
  'Which Post codes may be sanctioned at which Office Types (FR-UM-078)';

-- ROLE_MASTER (needed early for POST_ROLE_MAP)
CREATE TABLE IF NOT EXISTS um.role_master (
  role_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name       varchar(160) NOT NULL,
  role_category   um.role_category_t NOT NULL,
  division_code   varchar(40)
                  REFERENCES um.division_master (division_code),
  description     varchar(500),
  is_active       boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uk_role_name UNIQUE (role_name)
);

COMMENT ON TABLE um.role_master IS
  'Single role catalogue Citizen | DSR | Other Department (FR-UM-016); Application Admin is NOT a seed row (FR-UM-051)';

-- POST_ROLE_MAP (FR-UM-047 / FR-UM-050)
CREATE TABLE IF NOT EXISTS um.post_role_map (
  post_code  varchar(40) NOT NULL
             REFERENCES um.posts_master (post_code),
  role_id    bigint NOT NULL
             REFERENCES um.role_master (role_id),
  PRIMARY KEY (post_code, role_id)
);

CREATE INDEX IF NOT EXISTS ix_post_role_map_role
  ON um.post_role_map (role_id);

COMMENT ON TABLE um.post_role_map IS
  'Unmapped post cannot be sanctioned or assigned (FR-UM-047)';

-- SANCTIONED_POST (FR-UM-024, FR-UM-048, FR-UM-066–068)
CREATE TABLE IF NOT EXISTS um.sanctioned_post (
  post_code            varchar(40) NOT NULL
                       REFERENCES um.posts_master (post_code),
  office_code          varchar(40) NOT NULL
                       REFERENCES um.office_hierarchy (office_code),
  sanctioned_strength  integer     NOT NULL CHECK (sanctioned_strength >= 0),
  occupied_count       integer     NOT NULL DEFAULT 0 CHECK (occupied_count >= 0),
  remaining_capacity   integer GENERATED ALWAYS AS
                       (GREATEST(sanctioned_strength - occupied_count, 0)) STORED,
  is_wholly_unoccupied boolean GENERATED ALWAYS AS
                       (occupied_count = 0) STORED,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (post_code, office_code),
  CONSTRAINT ck_sanctioned_occupied
    CHECK (occupied_count <= sanctioned_strength + 1)
    -- +1 allows FR-UM-067 reserved handover at full strength during transition;
    -- application enforces normal capacity; job keeps count accurate.
);

COMMENT ON TABLE um.sanctioned_post IS
  'Approved headcount per Post at Office; occupied_count job-maintained (FR-UM-068)';

COMMENT ON COLUMN um.sanctioned_post.occupied_count IS
  'Active + Reserved occupancies; Temporary Absence does NOT reduce this (FR-UM-081)';
COMMENT ON COLUMN um.sanctioned_post.remaining_capacity IS
  'Persisted (generated), floored at 0 — FR-UM-066(a), FR-UM-068(3): GREATEST(sanctioned_strength - occupied_count, 0). During an FR-UM-067 handover, occupied_count may transiently exceed sanctioned_strength by 1 (outgoing officer still active + incoming reserved Transfer In); remaining_capacity reads 0, not negative, in that window.';
COMMENT ON COLUMN um.sanctioned_post.is_wholly_unoccupied IS
  'Persisted (generated) — FR-UM-066(b), FR-UM-068(3): true only when occupied_count = 0';
