-- =============================================================================
-- 05 · Identity — users, direct roles, Aadhaar e-KYC, email domains
-- Companion to ERD-K3-UM-001 v2.3 / BRD_User_Management_v1.0 (11-Sep-2026)
-- =============================================================================

SET search_path TO um, public;

-- OFFICIAL_EMAIL_DOMAIN (FR-UM-064) — Other Department official email allow-list
CREATE TABLE IF NOT EXISTS um.official_email_domain (
  domain     varchar(120) PRIMARY KEY,
  is_active  boolean NOT NULL DEFAULT true
);

COMMENT ON TABLE um.official_email_domain IS
  'Permitted official email domain allow-list for Other Department creation (FR-UM-064); empty = no domain restriction. DSR Officers do not capture official email (FR-UM-002, FR-UM-064).';

-- USER_MASTER
CREATE TABLE IF NOT EXISTS um.user_master (
  user_id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username                 varchar(80)  NOT NULL,
  user_category            um.user_category_t NOT NULL,
  first_name               varchar(100) NOT NULL,
  middle_name              varchar(100),
  last_name                varchar(100),
  email                    varchar(200),
  mobile                   varchar(20)  NOT NULL,
  kgid                     varchar(40),
  employee_id              varchar(40),
  department_code          varchar(40),
  parent_department        varchar(200),
  designation              varchar(200),
  account_end_date         date,
  status                   um.account_status_t NOT NULL DEFAULT 'ACTIVE',
  status_reason            varchar(500),
  lockout_until            timestamptz,
  reset_lockout_until      timestamptz,
  ekyc_verified_at         timestamptz,
  biometric_ref            varchar(200),
  photo_ref                varchar(200),
  id_proof_ref             varchar(200),
  authorisation_letter_ref varchar(200),
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),
  created_by               bigint,
  CONSTRAINT uk_user_username UNIQUE (username),
  CONSTRAINT ck_user_category_fields CHECK (
    (
      user_category = 'CITIZEN'
      AND email IS NOT NULL
      AND kgid IS NULL
      AND employee_id IS NULL
      AND department_code IS NULL
      AND parent_department IS NULL
    )
    OR (
      user_category = 'DSR_OFFICER'
      AND kgid IS NOT NULL
      AND username = kgid
      AND email IS NULL
      AND employee_id IS NULL
      AND department_code IS NULL
    )
    OR (
      user_category = 'OTHER_DEPARTMENT'
      AND email IS NOT NULL
      AND department_code IS NOT NULL
      AND parent_department IS NOT NULL
      AND (employee_id IS NOT NULL OR kgid IS NOT NULL)
      AND username = department_code || '-' || COALESCE(employee_id, kgid)
    )
  ),
  CONSTRAINT ck_biometric_dsr_only CHECK (
    biometric_ref IS NULL OR user_category = 'DSR_OFFICER'
  ),
  CONSTRAINT ck_ekyc_citizen_only CHECK (
    ekyc_verified_at IS NULL OR user_category = 'CITIZEN'
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_kgid_dsr
  ON um.user_master (kgid)
  WHERE kgid IS NOT NULL AND user_category = 'DSR_OFFICER';

CREATE INDEX IF NOT EXISTS ix_user_category ON um.user_master (user_category);
CREATE INDEX IF NOT EXISTS ix_user_email ON um.user_master (email);
CREATE INDEX IF NOT EXISTS ix_user_mobile ON um.user_master (mobile);
CREATE INDEX IF NOT EXISTS ix_user_status ON um.user_master (status);
CREATE INDEX IF NOT EXISTS ix_user_department_code ON um.user_master (department_code);

COMMENT ON TABLE um.user_master IS
  'Single user store. Username unique across all categories (Citizen preferred / DSR KGID / OD DeptCode-EmpID|KGID). Email and mobile are not unique (FR-UM-004, FR-UM-062). No password attribute (FR-UM-009).';
COMMENT ON COLUMN um.user_master.username IS
  'Only unique login identifier — Citizen preferred username; DSR = KGID; Other Department = <DepartmentCode>-<EmployeeID|KGID> (FR-UM-062, FR-UM-064)';
COMMENT ON COLUMN um.user_master.last_name IS
  'Nullable — single-name citizens are common; only first_name is mandatory';
COMMENT ON COLUMN um.user_master.email IS
  'Required for Citizen and Other Department; not captured for DSR Officers (FR-UM-002, FR-UM-064)';
COMMENT ON COLUMN um.user_master.kgid IS
  'Mandatory and unique for DSR Officers; equals username. Optional for Other Department when employee_id is used instead.';
COMMENT ON COLUMN um.user_master.ekyc_verified_at IS
  'Set when Citizen Aadhaar e-KYC succeeds at registration (FR-UM-085). Aadhaar number is never stored.';
COMMENT ON COLUMN um.user_master.biometric_ref IS
  'UIDAI-compliant face / biometric token for DSR Officer login (FR-UM-006). Not used for Other Department (FR-UM-007).';

-- USER_ROLE (Citizen / Other Department only)
CREATE TABLE IF NOT EXISTS um.user_role (
  user_id     bigint NOT NULL REFERENCES um.user_master (user_id),
  role_id     bigint NOT NULL REFERENCES um.role_master (role_id),
  assigned_at timestamptz NOT NULL DEFAULT now(),
  assigned_by bigint REFERENCES um.user_master (user_id),
  PRIMARY KEY (user_id, role_id)
);

CREATE INDEX IF NOT EXISTS ix_user_role_role ON um.user_role (role_id);

COMMENT ON TABLE um.user_role IS
  'Direct roles for Citizen (1..*) and Other Department (exactly 1); DSR uses Post–Role only (FR-UM-034, FR-UM-052)';

-- EKYC_CHALLENGE — Aadhaar e-KYC (FR-UM-085, FR-UM-056). Never stores Aadhaar number / VID.
CREATE TABLE IF NOT EXISTS um.ekyc_challenge (
  ekyc_id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id              bigint REFERENCES um.user_master (user_id),
  pending_token        varchar(64),
  purpose              um.ekyc_purpose_t NOT NULL,
  uidai_txn_ref        varchar(120),
  status               um.ekyc_status_t NOT NULL DEFAULT 'PENDING',
  consent_captured_at  timestamptz,
  attempt_count        integer NOT NULL DEFAULT 0,
  completed_at         timestamptz,
  created_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_ekyc_owner CHECK (
    user_id IS NOT NULL OR pending_token IS NOT NULL
  )
);

CREATE INDEX IF NOT EXISTS ix_ekyc_user ON um.ekyc_challenge (user_id);
CREATE INDEX IF NOT EXISTS ix_ekyc_pending ON um.ekyc_challenge (pending_token)
  WHERE pending_token IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_ekyc_status ON um.ekyc_challenge (status, created_at);

COMMENT ON TABLE um.ekyc_challenge IS
  'Aadhaar e-KYC attempts for Citizen registration and lost-mobile reset (FR-UM-085, FR-UM-056). Stores opaque UIDAI transaction refs only — never Aadhaar number or VID.';
