-- =============================================================================
-- 05 · Identity — users, direct roles, security Q&A, email domains
-- =============================================================================

SET search_path TO um, public;

-- OFFICIAL_EMAIL_DOMAIN (FR-UM-064)
CREATE TABLE IF NOT EXISTS um.official_email_domain (
  domain     varchar(120) PRIMARY KEY,
  is_active  boolean NOT NULL DEFAULT true
);

COMMENT ON TABLE um.official_email_domain IS
  'Permitted official email domain allow-list for DSR / Other Department creation (FR-UM-064); empty = no domain restriction enforced';

-- SECURITY_QUESTION (FR-UM-055)
CREATE TABLE IF NOT EXISTS um.security_question (
  question_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_text  varchar(500) NOT NULL,
  is_active      boolean NOT NULL DEFAULT true,
  display_order  integer NOT NULL DEFAULT 0
);

COMMENT ON TABLE um.security_question IS
  'Predefined list a Citizen picks 5 of at registration (FR-UM-055); 3 asked at random on lost-mobile reset (FR-UM-056)';

-- OFFICIAL_EMAIL_DOMAIN comment (added retroactively)

-- USER_MASTER
CREATE TABLE IF NOT EXISTS um.user_master (
  user_id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username                varchar(80)  NOT NULL,
  user_category           um.user_category_t NOT NULL,
  first_name              varchar(100) NOT NULL,
  middle_name             varchar(100),
  last_name               varchar(100),
  email                   varchar(200) NOT NULL,
  mobile                  varchar(20)  NOT NULL,
  parent_department       varchar(200),
  designation             varchar(200),
  account_end_date        date,
  status                  um.account_status_t NOT NULL DEFAULT 'ACTIVE',
  status_reason           varchar(500),
  lockout_until           timestamptz,
  reset_lockout_until     timestamptz,
  biometric_ref           varchar(200),
  photo_ref               varchar(200),
  id_proof_ref            varchar(200),
  authorisation_letter_ref varchar(200),
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),
  created_by              bigint,
  CONSTRAINT uk_user_username UNIQUE (username),
  CONSTRAINT ck_od_fields CHECK (
    user_category <> 'OTHER_DEPARTMENT'
    OR (parent_department IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS ix_user_category ON um.user_master (user_category);
CREATE INDEX IF NOT EXISTS ix_user_email ON um.user_master (email);
CREATE INDEX IF NOT EXISTS ix_user_mobile ON um.user_master (mobile);
CREATE INDEX IF NOT EXISTS ix_user_status ON um.user_master (status);

COMMENT ON TABLE um.user_master IS
  'Single user store; username unique (Citizen preferred / KGID); email & mobile NOT unique (FR-UM-004, FR-UM-062)';
COMMENT ON COLUMN um.user_master.username IS
  'Only unique login identifier across all categories — no password attribute (FR-UM-009)';
COMMENT ON COLUMN um.user_master.last_name IS
  'Nullable — single-name citizens are common; only first_name is mandatory';

-- USER_ROLE (Citizen / Other Department only)
CREATE TABLE IF NOT EXISTS um.user_role (
  user_id  bigint NOT NULL REFERENCES um.user_master (user_id),
  role_id  bigint NOT NULL REFERENCES um.role_master (role_id),
  assigned_at timestamptz NOT NULL DEFAULT now(),
  assigned_by bigint REFERENCES um.user_master (user_id),
  PRIMARY KEY (user_id, role_id)
);

CREATE INDEX IF NOT EXISTS ix_user_role_role ON um.user_role (role_id);

COMMENT ON TABLE um.user_role IS
  'Direct roles for Citizen (1..*) and Other Department (exactly 1); DSR uses Post–Role only';

-- USER_SECURITY_ANSWER (Citizen only — FR-UM-055)
CREATE TABLE IF NOT EXISTS um.user_security_answer (
  user_id      bigint NOT NULL REFERENCES um.user_master (user_id),
  question_id  bigint NOT NULL REFERENCES um.security_question (question_id),
  answer_hash  text   NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, question_id)
);

COMMENT ON TABLE um.user_security_answer IS
  'Exactly five distinct hashed answers per Citizen; never displayed (FR-UM-055)';
