-- =============================================================================
-- 06 · Occupancy, Temporary Absence, Temporary Charge
-- =============================================================================

SET search_path TO um, public;

-- POST_OCCUPANCY
CREATE TABLE IF NOT EXISTS um.post_occupancy (
  occupancy_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                bigint NOT NULL
                         REFERENCES um.user_master (user_id),
  post_code              varchar(40) NOT NULL,
  office_code            varchar(40) NOT NULL,
  status                 um.occupancy_status_t NOT NULL DEFAULT 'ACTIVE',
  joining_date           date,
  transfer_order_no      varchar(120),
  transfer_document_id   varchar(200),
  relieving_date         date,
  relieving_order_no     varchar(120),
  relieving_document_id  varchar(200),
  end_date               date,
  deputation_reason      varchar(80),
  reserved_flag          boolean NOT NULL DEFAULT false,
  created_by             bigint REFERENCES um.user_master (user_id),
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),
  ended_at               timestamptz,
  CONSTRAINT fk_occupancy_sanctioned
    FOREIGN KEY (post_code, office_code)
    REFERENCES um.sanctioned_post (post_code, office_code),
  CONSTRAINT ck_deputation_reason CHECK (
    (end_date IS NULL AND deputation_reason IS NULL)
    OR (end_date IS NOT NULL AND deputation_reason IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS ix_occupancy_user
  ON um.post_occupancy (user_id);
CREATE INDEX IF NOT EXISTS ix_occupancy_post_office
  ON um.post_occupancy (post_code, office_code);
CREATE INDEX IF NOT EXISTS ix_occupancy_status
  ON um.post_occupancy (status);
CREATE INDEX IF NOT EXISTS ix_occupancy_relieving
  ON um.post_occupancy (relieving_date) WHERE relieving_date IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_occupancy_end_date
  ON um.post_occupancy (end_date) WHERE end_date IS NOT NULL;

COMMENT ON TABLE um.post_occupancy IS
  'DSR user ↔ sanctioned Post+Office; Transfer In / Relieving / deputation as attributes';
COMMENT ON COLUMN um.post_occupancy.reserved_flag IS
  'FR-UM-067 reserved Transfer In — counts toward Occupied immediately';

-- TEMPORARY_ABSENCE (FR-UM-079–FR-UM-081, FR-UM-084)
CREATE TABLE IF NOT EXISTS um.temporary_absence (
  absence_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occupancy_id   bigint NOT NULL
                 REFERENCES um.post_occupancy (occupancy_id),
  absence_type   um.absence_type_t NOT NULL,
  reason_code    varchar(80) NOT NULL,
  from_date      date NOT NULL,
  to_date        date NOT NULL,
  order_ref      varchar(120),
  document_id    varchar(200),
  status         um.absence_status_t NOT NULL DEFAULT 'APPROVED',
  recorded_by    bigint NOT NULL
                 REFERENCES um.user_master (user_id),
  cancelled_by   bigint REFERENCES um.user_master (user_id),
  cancelled_at   timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_absence_dates CHECK (to_date >= from_date)
);

CREATE INDEX IF NOT EXISTS ix_absence_occupancy
  ON um.temporary_absence (occupancy_id);
CREATE INDEX IF NOT EXISTS ix_absence_window
  ON um.temporary_absence (from_date, to_date);
CREATE INDEX IF NOT EXISTS ix_absence_status
  ON um.temporary_absence (status);

-- At most one Approved absence overlapping a given occupancy is enforced in
-- application / function layer (date-range overlap). Partial unique below
-- prevents multiple open Approved rows without dates considered.
CREATE UNIQUE INDEX IF NOT EXISTS uk_absence_one_open_per_occupancy
  ON um.temporary_absence (occupancy_id)
  WHERE status = 'APPROVED';

COMMENT ON TABLE um.temporary_absence IS
  'Leave / OOD / Other on active occupancy; does not free capacity (FR-UM-079, FR-UM-081)';

-- TEMPORARY_CHARGE (FR-UM-082–FR-UM-084)
CREATE TABLE IF NOT EXISTS um.temporary_charge (
  temp_charge_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  absence_id           bigint NOT NULL
                       REFERENCES um.temporary_absence (absence_id),
  cover_user_id        bigint NOT NULL
                       REFERENCES um.user_master (user_id),
  covered_post_code    varchar(40) NOT NULL,
  covered_office_code  varchar(40) NOT NULL,
  from_date            date NOT NULL,
  to_date              date NOT NULL,
  status               um.temp_charge_status_t NOT NULL DEFAULT 'ACTIVE',
  assigned_by          bigint NOT NULL
                       REFERENCES um.user_master (user_id),
  order_ref            varchar(120),
  document_id          varchar(200),
  created_at           timestamptz NOT NULL DEFAULT now(),
  cancelled_at         timestamptz,
  CONSTRAINT fk_temp_charge_sanctioned
    FOREIGN KEY (covered_post_code, covered_office_code)
    REFERENCES um.sanctioned_post (post_code, office_code),
  CONSTRAINT ck_temp_charge_dates CHECK (to_date >= from_date)
);

CREATE INDEX IF NOT EXISTS ix_temp_charge_cover
  ON um.temporary_charge (cover_user_id);
CREATE INDEX IF NOT EXISTS ix_temp_charge_absence
  ON um.temporary_charge (absence_id);

-- ≤1 active temporary charge per Post + Office (FR-UM-082)
CREATE UNIQUE INDEX IF NOT EXISTS uk_temp_charge_one_active_per_post_office
  ON um.temporary_charge (covered_post_code, covered_office_code)
  WHERE status = 'ACTIVE';

COMMENT ON TABLE um.temporary_charge IS
  'Superior-assigned cover of absent Post+Office; distinct from FR-UM-053 (FR-UM-082)';
