-- =============================================================================
-- 07 · RBAC — modules, functions, resources, role–function mapping
-- =============================================================================

SET search_path TO um, public;

CREATE TABLE IF NOT EXISTS um.module_master (
  module_code  varchar(40)  PRIMARY KEY,
  module_name  varchar(160) NOT NULL,
  description  varchar(500),
  is_active    boolean      NOT NULL DEFAULT true,
  created_at   timestamptz  NOT NULL DEFAULT now(),
  updated_at   timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT uk_module_name UNIQUE (module_name)
);

COMMENT ON TABLE um.module_master IS
  'Catalogue of application modules — Registration of Documents, Marriage Registration, etc. (Section 6.5.6)';

CREATE TABLE IF NOT EXISTS um.module_function (
  function_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_code    varchar(40)  NOT NULL
                 REFERENCES um.module_master (module_code),
  function_code  varchar(40)  NOT NULL,
  function_name  varchar(80)  NOT NULL,
  description    varchar(500),
  is_active      boolean      NOT NULL DEFAULT true,
  CONSTRAINT uk_module_function UNIQUE (module_code, function_code),
  CONSTRAINT uk_module_function_code UNIQUE (function_code)
);

COMMENT ON TABLE um.module_function IS
  'VIEW, ADD, EDIT, APPROVE, SIGN, PRINT, DOWNLOAD, FN-UM-ADMIN, … (FR-UM-039)';
COMMENT ON COLUMN um.module_function.function_code IS
  'Globally unique code referenced by Resource Master and Role–Module–Function mapping, e.g. FN-DOC-VIEW';
COMMENT ON COLUMN um.module_function.function_name IS
  'Short privilege verb shown in UI, e.g. VIEW, ADD, EDIT, APPROVE, SIGN, PRINT, DOWNLOAD';

CREATE TABLE IF NOT EXISTS um.resource_master (
  resource_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_code  varchar(60) NOT NULL,
  function_id    bigint
                 REFERENCES um.module_function (function_id),
  resource_type  um.resource_type_t NOT NULL,
  http_method    varchar(16),
  path_pattern   varchar(500) NOT NULL,
  is_public      boolean NOT NULL DEFAULT false,
  is_active      boolean NOT NULL DEFAULT true,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uk_resource_code UNIQUE (resource_code),
  CONSTRAINT ck_resource_function_required CHECK (
    is_public OR function_id IS NOT NULL
  )
);

CREATE INDEX IF NOT EXISTS ix_resource_function
  ON um.resource_master (function_id);
CREATE INDEX IF NOT EXISTS ix_resource_path
  ON um.resource_master (resource_type, http_method, path_pattern);

COMMENT ON TABLE um.resource_master IS
  'API / URL linked to Module Function; deny-by-default unless is_public (FR-UM-040, FR-UM-041)';
COMMENT ON COLUMN um.resource_master.resource_code IS
  'Admin-defined unique identifier, e.g. RES-DOC-GET (Section 6.5.6 Resource Master attributes)';
COMMENT ON COLUMN um.resource_master.function_id IS
  'Required for non-public resources; NULL only allowed when is_public = true (FR-UM-041)';

CREATE TABLE IF NOT EXISTS um.role_module_function (
  role_id      bigint NOT NULL REFERENCES um.role_master (role_id),
  function_id  bigint NOT NULL REFERENCES um.module_function (function_id),
  PRIMARY KEY (role_id, function_id)
);

CREATE INDEX IF NOT EXISTS ix_rmf_function
  ON um.role_module_function (function_id);

COMMENT ON TABLE um.role_module_function IS
  'Role name must match Role Master exactly (FR-UM-050); Application Admin outside this map (FR-UM-051)';
