-- =============================================================================
-- 08 · Runtime — session, OTP, audit
-- =============================================================================

SET search_path TO um, public;

CREATE TABLE IF NOT EXISTS um.user_session (
  session_id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                 bigint NOT NULL
                          REFERENCES um.user_master (user_id),
  is_active               boolean NOT NULL DEFAULT true,
  session_context         um.session_context_t,
  assigned_occupancy_id   bigint
                          REFERENCES um.post_occupancy (occupancy_id),
  add_charge_post_code    varchar(40)
                          REFERENCES um.posts_master (post_code),
  add_charge_office_code  varchar(40)
                          REFERENCES um.office_hierarchy (office_code),
  temp_charge_id          bigint
                          REFERENCES um.temporary_charge (temp_charge_id),
  login_at                timestamptz NOT NULL DEFAULT now(),
  last_activity_at        timestamptz NOT NULL DEFAULT now(),
  expires_at              timestamptz NOT NULL,
  ended_at                timestamptz,
  end_reason              varchar(80),
  CONSTRAINT ck_session_context_fields CHECK (
    session_context IS NULL
    OR (
      session_context = 'ASSIGNED'
      AND assigned_occupancy_id IS NOT NULL
      AND add_charge_post_code IS NULL
      AND temp_charge_id IS NULL
    )
    OR (
      session_context = 'ADDITIONAL_CHARGE'
      AND add_charge_post_code IS NOT NULL
      AND add_charge_office_code IS NOT NULL
      AND temp_charge_id IS NULL
    )
    OR (
      session_context = 'TEMPORARY_CHARGE'
      AND temp_charge_id IS NOT NULL
      AND add_charge_post_code IS NULL
    )
  )
);

-- One active session per Username (FR-UM-076)
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_session_one_active
  ON um.user_session (user_id)
  WHERE is_active;

CREATE INDEX IF NOT EXISTS ix_session_occupancy
  ON um.user_session (assigned_occupancy_id);
CREATE INDEX IF NOT EXISTS ix_session_temp_charge
  ON um.user_session (temp_charge_id);

COMMENT ON TABLE um.user_session IS
  'Idle 15 min (FR-UM-074); absolute 8 h (FR-UM-075); last-login-wins (FR-UM-076)';

CREATE TABLE IF NOT EXISTS um.otp_challenge (
  challenge_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         bigint REFERENCES um.user_master (user_id),
  pending_token   varchar(64),
  purpose         um.otp_purpose_t NOT NULL,
  channel         um.otp_channel_t NOT NULL,
  destination     varchar(200) NOT NULL,
  code_hash       text NOT NULL,
  expires_at      timestamptz NOT NULL,
  attempt_count   integer NOT NULL DEFAULT 0,
  resend_count    integer NOT NULL DEFAULT 0,
  invalidated     boolean NOT NULL DEFAULT false,
  consumed_at     timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_otp_owner CHECK (
    user_id IS NOT NULL OR pending_token IS NOT NULL
  )
);

CREATE INDEX IF NOT EXISTS ix_otp_user ON um.otp_challenge (user_id);
CREATE INDEX IF NOT EXISTS ix_otp_pending ON um.otp_challenge (pending_token)
  WHERE pending_token IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_otp_expires ON um.otp_challenge (expires_at);

COMMENT ON TABLE um.otp_challenge IS
  'OTP/PIN challenges — login SMS only (FR-UM-010); policy FR-UM-069–FR-UM-072';

CREATE TABLE IF NOT EXISTS um.audit_log (
  audit_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id     bigint,
  actor_type   um.actor_type_t NOT NULL,
  action       varchar(80)  NOT NULL,
  entity       varchar(80)  NOT NULL,
  entity_id    varchar(80),
  before_json  jsonb,
  after_json   jsonb,
  reason       varchar(500),
  artefact_id  varchar(200),
  occurred_at  timestamptz NOT NULL DEFAULT now(),
  ip_address   inet,
  user_agent   varchar(400)
);

CREATE INDEX IF NOT EXISTS ix_audit_occurred ON um.audit_log (occurred_at);
CREATE INDEX IF NOT EXISTS ix_audit_actor ON um.audit_log (actor_id);
CREATE INDEX IF NOT EXISTS ix_audit_entity ON um.audit_log (entity, entity_id);

COMMENT ON TABLE um.audit_log IS
  'Append-only; retain ≥ 7 years; includes temporary absence / charge events (FR-UM-084)';

-- Prevent UPDATE/DELETE on audit_log
CREATE OR REPLACE RULE audit_log_no_update AS
  ON UPDATE TO um.audit_log DO INSTEAD NOTHING;
CREATE OR REPLACE RULE audit_log_no_delete AS
  ON DELETE TO um.audit_log DO INSTEAD NOTHING;
