# -*- coding: utf-8 -*-
"""Stamp duty Article determination masters (from Stamp_Duty_Article_Determination_Inputs workbook)."""

INTENTS = [['INT-01', 'Transfer of ownership / rights in property'],
 ['INT-02', 'Security for loan / debt (mortgage, pledge, hypothecation, charge)'],
 ['INT-03', 'Right to use property (lease / licence / hire)'],
 ['INT-04', 'Authorisation (Power of Attorney / appointment)'],
 ['INT-05', 'Division / distribution of property (partition, settlement, trust)'],
 ['INT-06', 'Business entity / company / securities'],
 ['INT-07', 'Agreement / contract'],
 ['INT-08', 'Cancellation / release / surrender / revocation'],
 ['INT-09', 'Bonds and guarantees'],
 ['INT-10', 'Personal / family status (adoption, divorce)'],
 ['INT-11', 'Declarations, certificates, copies and notarial instruments'],
 ['INT-12', 'Shipping, goods and trade documents']]

NATURES = [['DN-01', 'Acknowledgement', 'INT-11', '1'],
 ['DN-02', 'Administration Bond', 'INT-09', '2'],
 ['DN-03', 'Adoption Deed / Authority to Adopt', 'INT-10', '3'],
 ['DN-04', 'Affidavit / Declaration', 'INT-11', '4'],
 ['DN-05', 'Agreement / Memorandum of Agreement', 'INT-07', '5'],
 ['DN-06', 'Deposit of Title Deeds / Pawn / Pledge', 'INT-02', '6'],
 ['DN-07', 'Appointment in Execution of a Power', 'INT-04', '7'],
 ['DN-08', 'Appraisement / Valuation', 'INT-11', '8'],
 ['DN-09', 'Apprenticeship Deed', 'INT-07', '9'],
 ['DN-10', 'Articles of Association', 'INT-06', '10'],
 ['DN-11', 'Award (Arbitration)', 'INT-01', '11'],
 ['DN-12', 'Bond', 'INT-09', '12'],
 ['DN-13', 'Bottomry Bond', 'INT-12', '13'],
 ['DN-14', 'Cancellation of Instrument', 'INT-08', '14'],
 ['DN-15', 'Certificate of Sale (Public Auction)', 'INT-01', '15'],
 ['DN-16', 'Share Certificate / Document of title to shares', 'INT-06', '16'],
 ['DN-17', 'Certificate of Enrolment as Advocate', 'INT-11', '17'],
 ['DN-18', 'Charter Party', 'INT-12', '18'],
 ['DN-19', 'Clearance List (Stock Exchange)', 'INT-06', '18-A'],
 ['DN-20', 'Composition Deed', 'INT-07', '19'],
 ['DN-21', 'Conveyance / Sale Deed (incl. Flat, Amalgamation, Machinery, Securitisation, TDR)', 'INT-01', '20'],
 ['DN-22', 'Certified Copy / Extract', 'INT-11', '21'],
 ['DN-23', 'Counterpart / Duplicate', 'INT-11', '22'],
 ['DN-24', 'Customs / Excise Bond', 'INT-09', '23'],
 ['DN-25', 'Delivery Order (Goods)', 'INT-12', '24'],
 ['DN-26', 'Divorce Instrument', 'INT-10', '25'],
 ['DN-27', 'Exchange of Property', 'INT-01', '26'],
 ['DN-28', 'Further Charge on Mortgaged Property', 'INT-02', '27'],
 ['DN-29', 'Gift Deed', 'INT-01', '28'],
 ['DN-30', 'Indemnity Bond', 'INT-09', '29'],
 ['DN-31', 'Lease (incl. Sub-lease, Agreement to Let, Mining Lease / MDPA)', 'INT-03', '30'],
 ['DN-32', 'Letter of Allotment of Shares', 'INT-06', '31'],
 ['DN-33', 'Letter of Licence (Debtor - Creditors)', 'INT-07', '32'],
 ['DN-34', 'Licence of Immovable / Movable Property (Leave & Licence)', 'INT-03', '32-A'],
 ['DN-35', 'Memorandum of Association', 'INT-06', '33'],
 ['DN-36', 'Mortgage Deed (incl. Hypothecation, Collateral Security)', 'INT-02', '34'],
 ['DN-37', 'Mortgage of Crop', 'INT-02', '35'],
 ['DN-38', 'Notarial Act', 'INT-11', '36'],
 ['DN-39', 'Broker / Agent Note or Contract Note', 'INT-06', '37'],
 ['DN-40', 'Note of Protest by Master of Ship', 'INT-12', '38'],
 ['DN-41', 'Partition Deed', 'INT-05', '39'],
 ['DN-42', 'Partnership (Constitution / Reconstitution / Dissolution)', 'INT-06', '40'],
 ['DN-43', 'Limited Liability Partnership', 'INT-06', '40-A'],
 ['DN-44', 'Power of Attorney', 'INT-04', '41'],
 ['DN-45', 'Protest of Bill or Note', 'INT-11', '42'],
 ['DN-46', 'Protest by Master of Ship', 'INT-12', '43'],
 ['DN-47', 'Reconveyance of Mortgaged Property', 'INT-08', '44'],
 ['DN-48', 'Release Deed', 'INT-08', '45'],
 ['DN-49', 'Respondentia Bond', 'INT-12', '46'],
 ['DN-50', 'Security Bond / Surety Bond', 'INT-09', '47'],
 ['DN-51', 'Settlement Deed / Revocation of Settlement', 'INT-05', '48'],
 ['DN-52', 'Share Warrant to Bearer', 'INT-06', '49'],
 ['DN-53', 'Shipping Order', 'INT-12', '50'],
 ['DN-54', 'Surrender of Lease', 'INT-08', '51'],
 ['DN-55', 'Transfer (Debentures, Mortgage / Bond interest, Trust property)', 'INT-01', '52'],
 ['DN-56', 'Transfer / Assignment of Lease', 'INT-01', '53'],
 ['DN-57', 'Transfer of Licence', 'INT-01', '53-A'],
 ['DN-58', 'Trust (Declaration of Trust)', 'INT-05', '54'],
 ['DN-59', 'Warrant for Goods', 'INT-12', '55']]

AGREEMENT_SUBJECTS = [['AS-01', 'Sale of a bill of exchange', '5(a)'],
 ['AS-02', 'Purchase / sale of Government security', '5(b)'],
 ['AS-03', 'Purchase / sale of shares, stocks, debentures, marketable securities', '5(c)'],
 ['AS-04', 'Lease-cum-sale allotment of site / building / shed by an authority', '5(d)'],
 ['AS-05', 'Lease-cum-sale of Flat / Apartment by BDA / KHB', '5(da)'],
 ['AS-06', 'Sale of immovable property (Agreement to Sell)', '5(e)'],
 ['AS-07', 'Construction / Joint Development of immovable property (JDA)', '5(f)'],
 ['AS-08', 'Sale of movable property', '5(g)'],
 ['AS-09', 'Mortgage (agreement relating to mortgage)', '5(h)'],
 ['AS-10', 'Depository Participant - client (Demat account opening)', '5(i)'],
 ['AS-11', 'Stock broker / sub-broker - client', '5(i-a)'],
 ['AS-12', 'Advertisement / telecasting / broadcasting for business promotion', '5(i-b)'],
 ['AS-13', 'Assignment / transfer of Intellectual Property Rights', '5(i-c)'],
 ['AS-14', 'Building works / labour / services (Works Contract)', '5(i-d)'],
 ['AS-15', 'Chit Agreement (Sec 6, Chit Funds Act, 1982)', '5(i-e)'],
 ['AS-16', 'Any other agreement not otherwise provided for', '5(j)']]

POA_PURPOSES = [['PP-01', 'Only to present / admit execution / procure registration of document(s) of a single transaction', '41(a)'],
 ['PP-02', 'To act in a single transaction (other than registration only)', '41(b)'],
 ['PP-03', 'To act in more than one transaction or generally (General POA)', '41(c)/(d)/(h)'],
 ['PP-04', 'To sell immovable property', '41(e)/(eb)/others'],
 ['PP-05', 'Construction / Joint Development of immovable property (owner to developer)', '41(ea)'],
 ['PP-06', 'To sell Transferable Development Rights (TDR)', '41(ec)'],
 ['PP-07', 'Broker / agent: trading operations in marketable securities', '41(f)'],
 ['PP-08', 'Broker / agent: other trading operations governing such operations', '41(g)'],
 ['PP-09', 'Any other purpose', '41(h)']]

CONVEYANCE_TYPES = [['CT-01', 'Sale / transfer of property (general conveyance)', '20(1)'],
 ['CT-02',
  'Sale of Flat / Apartment / Unit by promoter, land owner or developer, or transfer of share in co-op society / company for a unit',
  '20(2)'],
 ['CT-03', 'Conveyance of Flat / Apartment by BDA / KHB', '20(3)'],
 ['CT-04', 'Order of High Court / NCLT / Tribunal: Amalgamation of companies', '20(4)(i)'],
 ['CT-05', 'Order of High Court / NCLT / Tribunal: Reconstruction / Demerger', '20(4)(ii)'],
 ['CT-06', 'Conveyance of industrial machinery', '20(5)'],
 ['CT-07', 'Assignment of receivables to SPV (securitisation under SARFAESI)', '20(6)'],
 ['CT-08', 'Conveyance of Transferable Development Rights (TDR)', '20(7)']]

GENERAL_RULES = [['GR-01',
  'System scope',
  'One transaction per application',
  'Each application covers one transaction (one Nature of document). Documents relating to several distinct matters (Sec 5 - aggregate '
  'duty) are not handled by the system.',
  'Step 3 allows selection of a single Nature of document only.'],
 ['GR-02',
  'Sec 6',
  'Instrument falling under two or more descriptions',
  'Chargeable only with the highest of such duties.',
  'Evaluate each matching rule; select maximum.'],
 ['GR-03',
  'Sec 4',
  'Several instruments for one sale / mortgage / settlement',
  'Principal instrument pays Schedule duty (highest of the set); every other instrument Rs. 100.',
  'Capture GEN-11; if Secondary -> Rs. 100; parties may designate principal.'],
 ['GR-04',
  'Sec 6 proviso / Art 22',
  'Counterpart / duplicate',
  'Counterpart of an instrument on which proper duty is paid: Art 22.',
  'Validate original document reference (MSC-09).'],
 ['GR-05',
  'Sec 45-A / 45-B',
  'Market value check',
  'For conveyance, gift 28(a), exchange, settlement 48-A(i), partnership 40-B(a) / 40-C(a), agreement 5(e)(i) / 5(f), lease 30(1)(vi), POA '
  '41(e)/(ea)/(eb), release 45(a), decree conveyance, award 11(a), trust 54(iii), TDR 20(7): duty on higher of declared value and guidance '
  'MV published by CVC.',
  "GEN-09 auto-fetched from Guidance Value module; 'Sec 45-A MV check' column in Article_Rules = Yes."],
 ['GR-06',
  'Schedule',
  "'or part thereof' rounding",
  "Wherever duty is 'per Rs. X or part thereof', the base is rounded UP to the next multiple of X.",
  'Implement CEILING(base / X) x rate.'],
 ['GR-07',
  'Schedule',
  'Minimum / maximum caps',
  'Apply the min / max stated for the clause after computing the ad valorem amount.',
  'Article_Rules columns Minimum / Maximum.'],
 ['GR-08',
  'Art 5 Expl. II, 41 provisos, 20(1) provisos',
  'Adjustment of duty already paid',
  'Duty paid on agreement 5(e)/5(h), POA 41(e)/(eb), lease-cum-sale 5(d)/5(da) is adjustable against the later conveyance / mortgage '
  'between the same parties for the same property.',
  'Capture GEN-12 / POA-04 with document reference; system verifies the earlier e-stamp / registration.'],
 ['GR-09',
  'Art 5(e), 5(g), 14',
  'Cancellation of agreement',
  'Deed cancelling a duly stamped 5(e)(i) / 5(g)(i) agreement between the same parties: max Rs. 500.',
  'AGR-15 flag.'],
 ['GR-10',
  'Art 30, 32-A',
  'Average annual rent',
  'Average annual rent = total rent for the term / number of years (for term < 1 year, rent for the term).',
  'Derived from LSE-03 rent schedule (captures escalation).'],
 ['GR-11',
  'Art 30, 32-A, 5(f), 41(ea)',
  'Money advanced',
  'Includes security deposit, whether refundable or adjustable.',
  'LSE-05 / AGR-13 always captured.'],
 ['GR-12', 'Art 41 Explanation', 'Counting attorneys', 'Persons belonging to the same firm count as one person.', 'POA-02 validation.'],
 ['GR-13',
  'Sec 3',
  'Exemptions',
  'Instruments listed as exempt under an Article (and Govt-executed instruments exempt under Sec 3) carry no duty.',
  'Exemption inputs (Purpose = E) are checked before calculation.']]

