# -*- coding: utf-8 -*-
"""Create BRD_Marriage_v1.13.docx from v1.12.

Populate §3 Legal and regulatory reference with applicable Acts, relevant sections,
Karnataka Rules, notifications and statutory forms mapping — sourced from
Acts_Rules/Marriage/.
"""
from __future__ import annotations

import shutil
import sys
from copy import deepcopy
from pathlib import Path

from docx import Document
from docx.oxml.ns import qn
from docx.shared import Pt
from docx.table import Table, _Cell
from docx.text.paragraph import Paragraph

sys.stdout.reconfigure(encoding="utf-8")

BASE = Path(r"E:\MVP\Kaveri 3.0\Source Code\Kaveri 3 Plan\Finalized BRD\Marriage\RFP")
SRC = BASE / "BRD_Marriage_v1.12.docx"
DST = BASE / "BRD_Marriage_v1.13.docx"

HMA_FORM_ROWS = [
    ["Form", "Rule ref", "Purpose", "Generated by"],
    [
        "Form I",
        "Rule 4",
        "Memorandum of marriage (duplicate)",
        "System from captured data + joint photo",
    ],
    [
        "Form IA",
        "Rule 4(2)",
        "Application for filing of marriage memorandum",
        "System from captured data + declarations",
    ],
    [
        "Form II",
        "Rule 4(4)",
        "Endorsement on reverse of memorandum and duplicate: date received; serial no.; "
        "page; volume of Register under HMA 1955; Registrar signature",
        "System on SR digital signature (both channels); blank template in Offline "
        "printout pack before endorsement",
    ],
    [
        "Form II-A",
        "Rule 4(5)",
        "Certificate of registration of marriage under HMA 1955",
        "System on approval / SR DSC",
    ],
    [
        "Form III",
        "Rule 5(1)",
        "Certificate affixed to monthly duplicate memoranda bundle",
        "Back-office batch export",
    ],
    [
        "Form IV / V",
        "Rules 5(2), 6",
        "Indices of register entries",
        "Reporting / search",
    ],
    [
        "Form VI",
        "Rule 9",
        "Fee receipt",
        "Payment integration",
    ],
]

SMA_FORM_ROWS = [
    ["Form / Schedule", "Act ref", "Purpose", "Generated by"],
    [
        "Notice of Intended Marriage (Second Schedule)",
        "Sec. 5 / Sec. 6",
        "Statutory notice for Intended Marriage",
        "System + SR generation; portal / notice-board publication",
    ],
    [
        "Declarations (Third Schedule)",
        "Sec. 11",
        "Declarations by parties and witnesses before solemnization",
        "System / office capture",
    ],
    [
        "Certificate of Marriage (Fourth Schedule)",
        "Sec. 13",
        "Certificate after solemnization under Chapter II",
        "System on SR DSC",
    ],
    [
        "Certificate of Marriage (Fifth Schedule)",
        "Sec. 16",
        "Certificate for marriages registered under Chapter III (Other Forms)",
        "System on SR DSC",
    ],
    [
        "Form I / II (Karnataka Rules)",
        "Rule 6(4)",
        "Notice / summons for objection enquiry",
        "System on objection workflow",
    ],
    [
        "Form III (Karnataka Rules)",
        "Rule 7(1)",
        "Application for registration of marriage celebrated in other forms",
        "System on Other Forms path",
    ],
    [
        "Form IV (Karnataka Rules)",
        "Rule 11",
        "Certified copy of entries transmitted to Registrar-General",
        "Back-office quarterly export",
    ],
]

TOC_SECTION_3 = [
    "3.1 Applicable Acts",
    "3.2 Relevant sections followed by the Department for Marriage Registration",
    "3.3 Relevant rules followed by the Department for Marriage Registration",
    "3.4 Relevant notifications issued by the Department for Marriage Registration",
    "3.5 Hindu Marriage statutory forms mapping",
    "3.6 Special Marriage statutory forms mapping",
]


def set_para_text(paragraph: Paragraph, text: str) -> None:
    if not paragraph.runs:
        paragraph.add_run(text)
        return
    paragraph.runs[0].text = text
    for r in paragraph.runs[1:]:
        r.text = ""


def set_cell_text(cell: _Cell, text: str) -> None:
    paras = cell.paragraphs
    if not paras:
        cell.add_paragraph(text)
        return
    set_para_text(paras[0], text)
    for p in paras[1:]:
        set_para_text(p, "")


def set_row(table: Table, ri: int, values: list[str]) -> None:
    row = table.rows[ri]
    for ci, val in enumerate(values):
        if ci < len(row.cells):
            set_cell_text(row.cells[ci], val)


def add_version_row(table: Table, values: list[str]) -> None:
    table._tbl.append(deepcopy(table.rows[-1]._tr))
    set_row(table, len(table.rows) - 1, values)


def style_name(paragraph: Paragraph) -> str:
    return str(paragraph.style.name) if paragraph.style else ""


def find_para(
    doc: Document,
    exact: str | None = None,
    contains: str | None = None,
    heading_only: bool = False,
) -> Paragraph:
    for p in doc.paragraphs:
        if heading_only and not style_name(p).startswith("Heading"):
            continue
        t = p.text.strip()
        if exact is not None and t == exact:
            return p
        if contains is not None and contains in t:
            return p
    raise KeyError(f"Paragraph not found: exact={exact!r} contains={contains!r}")


def insert_paragraph_after(
    paragraph: Paragraph, text: str = "", style: str | None = None
) -> Paragraph:
    new_p = deepcopy(paragraph._p)
    pPr = new_p.find(qn("w:pPr"))
    for child in list(new_p):
        if child is not pPr:
            new_p.remove(child)
    paragraph._p.addnext(new_p)
    new_para = Paragraph(new_p, paragraph._parent)
    if style:
        new_para.style = style
    if text:
        new_para.add_run(text)
    return new_para


def insert_table_after(paragraph: Paragraph, rows: list[list[str]], doc: Document) -> Paragraph:
    """Insert table after paragraph; return a trailing empty paragraph for further inserts."""
    table = doc.add_table(rows=len(rows), cols=len(rows[0]))
    table.style = "Table Grid"
    for i, row_data in enumerate(rows):
        for j, val in enumerate(row_data):
            cell = table.rows[i].cells[j]
            cell.text = val
            for p in cell.paragraphs:
                for run in p.runs:
                    run.font.size = Pt(9)
    for cell in table.rows[0].cells:
        for p in cell.paragraphs:
            for run in p.runs:
                run.bold = True
                run.font.size = Pt(9)
    tbl = table._tbl
    tbl.getparent().remove(tbl)
    paragraph._p.addnext(tbl)
    tail = deepcopy(paragraph._p)
    pPr = tail.find(qn("w:pPr"))
    for child in list(tail):
        if child is not pPr:
            tail.remove(child)
    tbl.addnext(tail)
    return Paragraph(tail, paragraph._parent)


def clear_elements_after_until(paragraph: Paragraph, stop_paragraph: Paragraph) -> None:
    """Remove all body elements after `paragraph` until (but not including) `stop_paragraph`."""
    parent = paragraph._parent._element
    stop_el = stop_paragraph._element
    nxt = paragraph._element.getnext()
    while nxt is not None and nxt is not stop_el:
        to_remove = nxt
        nxt = nxt.getnext()
        parent.remove(to_remove)


def replace_toc_section_3(doc: Document) -> None:
    anchor = find_para(doc, exact="3. Legal and regulatory reference")
    # Remove old 3.x TOC lines until 4. Stakeholders
    nxt = anchor._element.getnext()
    while nxt is not None:
        if nxt.tag == qn("w:p"):
            texts = "".join(t.text or "" for t in nxt.iter(qn("w:t"))).strip()
            if texts == "4. Stakeholders and actors":
                break
            if texts.startswith("3."):
                to_remove = nxt
                nxt = nxt.getnext()
                to_remove.getparent().remove(to_remove)
                continue
        nxt = nxt.getnext()
    cursor = anchor
    for entry in TOC_SECTION_3:
        cursor = insert_paragraph_after(cursor, entry, style="Normal")


def build_section_3(doc: Document) -> None:
    h3 = find_para(doc, exact="3. Legal and regulatory reference", heading_only=True)
    h4 = find_para(doc, exact="4. Stakeholders and actors", heading_only=True)
    clear_elements_after_until(h3, h4)

    citation = (
        "Citation convention: Act = primary Central legislation; Rules = Karnataka "
        "subordinate legislation made under the Act; Notification = Gazette / "
        "Government Order cited in the Rules or issued separately. Source folder: "
        "Acts_Rules/Marriage/. Phase 1 scope (§2.1) covers Hindu Marriage and "
        "Special Marriage only; the Parsi Marriage and Divorce Act, 1936 is listed "
        "for reference but is out of scope unless promoted by the Project Owner."
    )
    cursor = insert_paragraph_after(h3, citation, style="Normal")

    # 3.1 Applicable Acts
    cursor = insert_paragraph_after(
        cursor, "3.1 Applicable Acts", style="Heading 3"
    )
    p31 = insert_paragraph_after(
        cursor,
        "The Department for Marriage Registration (through Sub-Registrars / Marriage "
        "Officers) administers the following Central Acts and Karnataka Rules in "
        "Kaveri 3.0 Phase 1:",
        style="Normal",
    )
    acts_rows = [
        ["Act", "Central Act No.", "Scope in Kaveri 3.0", "Source file"],
        [
            "The Hindu Marriage Act, 1955",
            "25 of 1955",
            "Registration of Hindu marriages (Sec. 8); conditions for marriage (Sec. 5); "
            "ceremonies (Sec. 7)",
            "Hindu Marriage Act, 1955.pdf",
        ],
        [
            "The Special Marriage Act, 1954",
            "43 of 1954",
            "Solemnization of special marriages (Chapter II); registration of marriages "
            "celebrated in other forms (Chapter III)",
            "The Special Marriage Act, 1954.pdf",
        ],
        [
            "The Indian Registration Act, 1908",
            "16 of 1908",
            "Appointment of Sub-Registrars who act as Hindu Marriage Registrars / "
            "Marriage Officers",
            "Cited in Karnataka Rules (S.O. 4896)",
        ],
        [
            "The Parsi Marriage and Divorce Act, 1936",
            "3 of 1936",
            "Out of scope — Phase 1 (reference only)",
            "THE PARSI MARRIAGE AND DIVORCE ACT, 1936.pdf",
        ],
    ]
    cursor = insert_table_after(p31, acts_rows, doc)

    # 3.2 Relevant sections
    cursor = insert_paragraph_after(
        cursor,
        "3.2 Relevant sections followed by the Department for Marriage Registration",
        style="Heading 3",
    )
    cursor = insert_paragraph_after(
        cursor,
        "Selected sections that drive Kaveri 3.0 business rules, validations and "
        "statutory outputs. Full text in the cited source files.",
        style="Normal",
    )
    cursor = insert_paragraph_after(
        cursor,
        "3.2.1 Hindu Marriage Act, 1955 (selected sections for registration)",
        style="Heading 4",
    )
    p_hma = insert_paragraph_after(
        cursor,
        "Source: Acts_Rules/Marriage/Hindu Marriage Act, 1955.pdf",
        style="Normal",
    )
    hma_section_rows = [
        ["Section", "Topic", "BRD relevance"],
        [
            "Sec. 2",
            "Application of Act",
            "Eligibility — Hindus (incl. Virashaiva, Lingayat, Brahmo/Prarthana/Arya Samaj), "
            "Buddhists, Jainas, Sikhs; excludes Scheduled Tribes unless notified",
        ],
        [
            "Sec. 3",
            "Definitions",
            "Sapinda relationship and degrees of prohibited relationship — validation rules",
        ],
        [
            "Sec. 5",
            "Conditions for a Hindu marriage",
            "Age (bridegroom ≥ 21, bride ≥ 18); no living spouse; consent; prohibited degrees / "
            "sapinda unless custom permits — Form IA declarations",
        ],
        [
            "Sec. 7",
            "Ceremonies for a Hindu marriage",
            "Customary rites and ceremonies; Saptapadi — solemnization evidence",
        ],
        [
            "Sec. 8",
            "Registration of Hindu marriages",
            "State rules power; register open for inspection; certified extracts; validity of "
            "marriage not affected by omission to register",
        ],
        [
            "Sec. 11–12",
            "Void / voidable marriages",
            "Optional SRO flags — not automated court nullity workflow",
        ],
        [
            "Sec. 17",
            "Punishment of bigamy",
            "Messaging linked to Sec. 5(i) declaration",
        ],
        [
            "Sec. 18",
            "Punishment for other Sec. 5 breaches",
            "Citizen / SRO awareness — not automated prosecution",
        ],
    ]
    cursor = insert_table_after(p_hma, hma_section_rows, doc)

    cursor = insert_paragraph_after(
        cursor,
        "3.2.2 Special Marriage Act, 1954 (selected sections)",
        style="Heading 4",
    )
    p_sma = insert_paragraph_after(
        cursor,
        "Source: Acts_Rules/Marriage/The Special Marriage Act, 1954.pdf",
        style="Normal",
    )
    sma_section_rows = [
        ["Section", "Topic", "BRD relevance"],
        [
            "Sec. 4",
            "Conditions relating to solemnization",
            "Eligibility / prerequisite checks before notice",
        ],
        [
            "Sec. 5",
            "Notice of intended marriage (Second Schedule)",
            "Generate and capture notice; jurisdiction — ≥ 30 days residence of at least one party",
        ],
        [
            "Sec. 6",
            "Marriage Notice Book and publication",
            "Enter notice; publish on portal and/or notice board; transmit if party resides elsewhere",
        ],
        [
            "Sec. 7",
            "Objection to marriage (30 days)",
            "30-day countdown from publication; accept and record objections",
        ],
        [
            "Sec. 8–9",
            "Procedure / enquiry on objection",
            "SR enquiry; summon parties; uphold or reject objection",
        ],
        [
            "Sec. 11",
            "Declaration by parties and witnesses (Third Schedule)",
            "Declarations before solemnization; three witnesses",
        ],
        [
            "Sec. 12–13",
            "Solemnization and certificate of marriage (Fourth Schedule)",
            "Office solemnization; certificate issuance",
        ],
        [
            "Sec. 14",
            "New notice if not solemnized within three months",
            "Block registration outside validity; require fresh notice",
        ],
        [
            "Sec. 15",
            "Registration of marriages celebrated in other forms",
            "Other Forms eligibility — ceremony performed; parties living together; ages; "
            "residence ≥ 30 days",
        ],
        [
            "Sec. 16",
            "Procedure for registration — Other Forms (Fifth Schedule)",
            "Public notice; 30-day objections; certificate with three witnesses",
        ],
        [
            "Sec. 47–48",
            "Marriage Certificate Book; transmission to Registrar-General",
            "Inspection; certified extracts; quarterly transmission",
        ],
    ]
    cursor = insert_table_after(p_sma, sma_section_rows, doc)

    # 3.3 Relevant rules
    cursor = insert_paragraph_after(
        cursor,
        "3.3 Relevant rules followed by the Department for Marriage Registration",
        style="Heading 3",
    )
    cursor = insert_paragraph_after(
        cursor,
        "Karnataka subordinate legislation made under the Hindu Marriage Act, 1955 "
        "(Sec. 8) and the Special Marriage Act, 1954 (Sec. 50).",
        style="Normal",
    )
    cursor = insert_paragraph_after(
        cursor,
        "3.3.1 Registration of Hindu Marriage (Karnataka) Rules, 1966",
        style="Heading 4",
    )
    p_hma_rules = insert_paragraph_after(
        cursor,
        "Source: Acts_Rules/Marriage/REGISTRATIONOFHINDUMARRIAGE_KARNATAKARULES_1966.docx. "
        "Made under HMA Sec. 8(1); G.S.R. 911 dated 10 March 1966; published Karnataka "
        "Gazette 28 April 1966, Part IV Section 2-C-1.",
        style="Normal",
    )
    hma_rule_rows = [
        ["Rule", "Requirement", "System feature"],
        [
            "Rule 2",
            "Definitions — Act, form, Marriage, Memorandum, Priest, Register, Registrar, "
            "Registrar-General, witness",
            "Glossary; eligibility validation",
        ],
        [
            "Rule 3(1) + S.O. 4896",
            "Appointment of Registrars; all Sub-Registrars under Registration Act 1908 "
            "appointed Registrars for their jurisdictions (HD 6 CIM 61, 4 Jul 1966)",
            "Office / jurisdiction master; route to correct SRO",
        ],
        [
            "Rule 4(1)",
            "Parties prepare and sign Form I in duplicate; deliver in person, registered post "
            "or electronically; jurisdiction = marriage place or ordinary residence of "
            "bridegroom/bride",
            "Online / Offline filing; office selection",
        ],
        [
            "Rule 4(2)",
            "Memorandum delivered with application in Form IA",
            "Linked application record",
        ],
        [
            "Rule 4(3)",
            "Memorandum and duplicate signed by three witnesses",
            "Three witness records + eSign / physical signature",
        ],
        [
            "Rule 4(4)",
            "Endorsement in Form II; paste in paste-book register or stored electronically",
            "Serial no., page, volume or electronic register entry",
        ],
        [
            "Rule 4(5)",
            "On completion of registration, immediately issue Form II-A certificate",
            "Certificate PDF + download / post / counter",
        ],
        [
            "Rule 5",
            "Monthly duplicate memoranda to Registrar-General with Form III certificate",
            "Monthly batch / Form III export",
        ],
        [
            "Rule 6",
            "Indices Forms IV and V at every Registrar",
            "Search / MIS indexes",
        ],
        [
            "Rule 6A",
            "Power to require duplicate / Form IA / remedy defects; forward if outside "
            "jurisdiction; scrutinise and refuse with brief written order",
            "Defect workflow; forward; refusal letter",
        ],
        [
            "Rule 8 + Schedule",
            "Certified extracts on application + fee; search fee provisions",
            "Certified extract service; fee master",
        ],
        [
            "Rule 9",
            "Receipt in Form VI for every fee; credit to State Government",
            "Payment receipt / reconciliation",
        ],
        [
            "Rule 10",
            "Custody and preservation of registers and records",
            "Retention / archival policy",
        ],
    ]
    cursor = insert_table_after(p_hma_rules, hma_rule_rows, doc)

    cursor = insert_paragraph_after(
        cursor,
        "3.3.2 Special Marriage (Karnataka) Rules, 1961",
        style="Heading 4",
    )
    p_sma_rules = insert_paragraph_after(
        cursor,
        "Source: Acts_Rules/Marriage/SpecialMarriage(Karnataka)Rules1961.pdf and "
        "Acts_Rules/Marriage/SpecialMarriageFees.docx. Notification No. HD 13MCIM 59(1), "
        "dated 2 May 1961. Made under SMA Sec. 50.",
        style="Normal",
    )
    sma_rule_rows = [
        ["Rule", "Requirement", "System feature"],
        [
            "Rule 3",
            "Marriage Officer shall display name, designation and working hours in English "
            "and Kannada",
            "Office master / public display",
        ],
        [
            "Rule 4",
            "Notice in Second Schedule form; in person or registered post; fee on delivery; "
            "serial number and Marriage Notice Book entry; exhibition of true copy",
            "Notice generation; serial no.; portal / notice-board publication",
        ],
        [
            "Rule 6",
            "Objection enquiry — recording, summons (Forms I & II), 30-day enquiry window, "
            "decision in writing",
            "Objection management workflow (FR-SMA-022–028)",
        ],
        [
            "Rule 7",
            "Application for registration of marriage in other forms (Form III); public "
            "notice exhibition; 30-day objection period",
            "Other Forms notice and registration path",
        ],
        [
            "Rule 8",
            "Solemnization outside office on application + additional fee",
            "Optional out-of-office solemnization fee",
        ],
        [
            "Rule 9",
            "Marriage Certificate Book — bound volume, consecutive numbering, index",
            "Register entry and certificate numbering",
        ],
        [
            "Rule 10",
            "Fee schedule — notice fee, registration fee, objection fee, certified copy, "
            "search, process fee, out-of-office solemnization",
            "First Payment (notice) and Second Payment (registration) per fee schedule",
        ],
        [
            "Rule 11",
            "Quarterly certified copies of entries to Registrar-General (Form IV)",
            "Back-office quarterly export",
        ],
    ]
    cursor = insert_table_after(p_sma_rules, sma_rule_rows, doc)

    # 3.4 Notifications
    cursor = insert_paragraph_after(
        cursor,
        "3.4 Relevant notifications issued by the Department for Marriage Registration",
        style="Heading 3",
    )
    p_notif = insert_paragraph_after(
        cursor,
        "Gazette notifications, Government Orders and amendments cited in the Karnataka "
        "Rules or issued under the Acts. Source folder: Acts_Rules/Marriage/.",
        style="Normal",
    )
    notif_rows = [
        ["Instrument", "Date / No.", "Effect", "BRD relevance", "Source"],
        [
            "S.O. 4896 / HD 6 CIM 61",
            "4 Jul 1966",
            "Appoints all Sub-Registrars as Registrars of Hindu Marriages for their "
            "jurisdictions",
            "Office master; A-01 assumption",
            "Embedded in Rules 1966 docx",
        ],
        [
            "Registration of Hindu Marriages (Karnataka) (Amendment) Rules, 1999",
            "w.e.f. 8 Jun 2000",
            "Priest / witness definitions; Form IA; three-witness signing; Form II-A "
            "immediate certificate; scrutiny / refusal order; Schedule fees",
            "Forms IA & II-A; SR scrutiny workflow",
            "Rules 1966 docx amendment notes",
        ],
        [
            "G.S.R. 314 / G.S.R. 394 / HD 5 PIM 69",
            "1968–1969",
            "Substitutions / additions to Rule 4 jurisdiction and memorandum clauses",
            "Historical Rule 4(1) text",
            "Rules 1966 docx",
        ],
        [
            "RD/48/MNMU/2023 — Registration of Hindu Marriage (Karnataka) (Amendment) "
            "Rules, 2024",
            "Gazette 06-Feb-2024, Part-IVA No. 60; under HMA Sec. 8(1)",
            "Amends Rule 4: insert 'or electronically' (r.4(1)); 'or stored electronically' "
            "(r.4(4)); 'or stored in electronic media' (r.4(5))",
            "Legal foundation for Online channel, electronic register and e-certificate",
            "RD48MNMU2023-Notification-marriage.pdf",
        ],
        [
            "Special Marriage (Karnataka) Rules, 1961",
            "Notification No. HD 13MCIM 59(1), 2 May 1961",
            "Original notification making the Karnataka Special Marriage Rules",
            "Special Marriage notice, objection, registration and fee procedures",
            "SpecialMarriage(Karnataka)Rules1961.pdf; SpecialMarriageFees.docx",
        ],
    ]
    cursor = insert_table_after(p_notif, notif_rows, doc)

    # 3.5 / 3.6 Forms mapping
    cursor = insert_paragraph_after(
        cursor, "3.5 Hindu Marriage statutory forms mapping", style="Heading 3"
    )
    p_hma_forms = insert_paragraph_after(
        cursor,
        "Forms under the Registration of Hindu Marriage (Karnataka) Rules, 1966. "
        "Source: Acts_Rules/Marriage/Form1.pdf and hindu marriage forms.pdf.",
        style="Normal",
    )
    cursor = insert_table_after(p_hma_forms, HMA_FORM_ROWS, doc)

    cursor = insert_paragraph_after(
        cursor, "3.6 Special Marriage statutory forms mapping", style="Heading 3"
    )
    p_sma_forms = insert_paragraph_after(
        cursor,
        "Schedules under the Special Marriage Act, 1954 and forms under the Special "
        "Marriage (Karnataka) Rules, 1961 (as applicable in Kaveri 3.0):",
        style="Normal",
    )
    insert_table_after(p_sma_forms, SMA_FORM_ROWS, doc)


def main() -> None:
    if not SRC.exists():
        raise FileNotFoundError(SRC)
    shutil.copy2(SRC, DST)
    doc = Document(str(DST))

    set_cell_text(doc.tables[0].rows[2].cells[1], "1.13")
    set_cell_text(doc.tables[0].rows[11].cells[1], "2026-09-01")
    add_version_row(
        doc.tables[1],
        [
            "1.13",
            "2026-09-01",
            "Nandha Kumar",
            "Populate §3 Legal and regulatory reference — applicable Acts, relevant "
            "sections, Karnataka Rules, notifications and statutory forms mapping "
            "(Acts_Rules/Marriage/)",
            "Prashanth",
        ],
    )

    replace_toc_section_3(doc)
    build_section_3(doc)

    doc.save(str(DST))
    print(f"Wrote {DST}")

    doc2 = Document(str(DST))
    print("Version:", doc2.tables[0].rows[2].cells[1].text.strip())
    h3_count = sum(
        1
        for p in doc2.paragraphs
        if style_name(p).startswith("Heading") and p.text.strip().startswith("3.")
    )
    print("Section 3 headings:", h3_count)
    acts = find_para(doc2, contains="3.1 Applicable Acts", heading_only=True)
    print("Has 3.1:", acts.text)


if __name__ == "__main__":
    main()
